<p><img alt="DataOwl" width=150 src="http://gwsolutions.cl/Images/dataowl.png", align="left", hspace=0, vspace=5></p>

<h1 align="center">Numpy y Pandas</h1>

<h4 align="center">Arreglos y Dataframes</h4>
<pre><div align="center"> La idea de este notebook es que sirva para iniciarse en el preprocesamiento de datos.</div>


<div align="right"> En términos de código y estructura, este notebook esta basado en el BootCamp 
<a href="https://github.com/Shekhar-rv/Python-for-Data-Science-and-Machine-Learning-Bootcamp">Python for Data Science and Machine Learning</a>.
.</div></pre>

## ¿Qué es Numpy?

<p><img alt="Numpy" width=70 src="https://user-images.githubusercontent.com/50221806/81123350-b7c5bb00-8ee7-11ea-9bfc-88f676c80315.png", align="right", hspace=0, vspace=5></p>

NumPy es una extensión de Python, que le agrega mayor soporte para vectores y matrices, constituyendo una biblioteca de funciones matemáticas de alto nivel para operar con esos vectores o matrices.

Para instalar la librería puede hacerse a través del comando **pip** o el comando **conda** en la consola de comandos:





```cmd
conda install numpy

pip install numpy
```

In [1]:
# Importando la librería

import numpy as np

Numpy nos permite crear y trabajar con vectores (llamados arreglos) y matrices de forma simple, y se enfoca principalmente en añadir funciones matematicas, a diferencia de las listas que son estructuras de mayor complejidad. Existen varias maneras de construir un arreglo, entre ellas la más sencilla es realizarlo a partir de una lista, no obstante, podemos hacerlo a partir de una matriz o de comandos predefinidos.

In [2]:
# Creando arreglo a partir de una lista

my_list = [1,2,3,4,5]
my_array = np.array(my_list)

my_array

array([1, 2, 3, 4, 5])

In [3]:
# Creando arreglo a partir de una lista de listas


my_list_of_lists = [ [1,2,3] , [4,5,6] , [7,8,9] ]
my_array_2 = np.array(my_list_of_lists)

my_array_2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
# Definiendo un array ordenado (Función arange)

arr = np.arange(1,11)

arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
# Definiendo un array de ceros (Función zeros)

arr_0 = np.zeros(10)

arr_0

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
# Definiendo un array de unos (Función ones)

arr_1 = np.ones(10)

arr_1

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [7]:
# Definiendo un arreglo equiespaciado

arr = np.linspace(0,1,15)

arr

array([0.        , 0.07142857, 0.14285714, 0.21428571, 0.28571429,
       0.35714286, 0.42857143, 0.5       , 0.57142857, 0.64285714,
       0.71428571, 0.78571429, 0.85714286, 0.92857143, 1.        ])

In [8]:
# Definiendo la matriz identidad


arr = np.eye(4)

arr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

Además de la creación de arreglos, existen además maneras de indexar y operaciones alrededor de los arreglos, no obstante no porfundizaremos en ellos ya que hoy en día esta librería no se utiliza en demasía, por lo que pasaremos a Pandas.

## ¿Qué es Pandas?
<p><img alt="Pandas" width=150 src="https://zhihuicao.files.wordpress.com/2016/05/pandas.png?w=399", align="right", hspace=0, vspace=5></p>

Pandas es una biblioteca de software escrita como extensión de NumPy para manipulación y análisis de datos para el lenguaje de programación Python. En particular, ofrece estructuras de datos y operaciones para manipular tablas numéricas y series temporales. 

Para instalar la librería puede hacerse a través del comando **pip** o el comando **conda** en la consola de comandos:



```cmd
conda install pandas

pip install pandas
```

In [9]:
#Importando la librería

import pandas as pd

<h3>Secciones</h3>

<div class="alert alert-danger" role="alert">
<ol>
    <li><a href="#section1"> Series</a></li>
    <li><a href="#section2"> DataFrames </a></li>
    <li><a href="#section3"> Datos faltantes (Missing Data) </a></li>
    <li><a href="#section4"> Agrupaciones (Groupby)</a></li>
    <li><a href="#section5"> Fusiones (Merge), Uniones (Join) y Concatenaciones</a></li>
</ol>
</div>
<hr>

<a id="section1"></a>
<h3>1. Series</h3>
<hr>

El primer tipo de datos principal que aprenderemos para los pandas es el tipo de datos **Serie**. Importemos Pandas y exploremos el objeto Serie.

<p><img alt="Dataframe" width=150 src="https://miro.medium.com/max/1284/1*iI8ltITQlsrX7Mc6E-OKKg.png", align="center", hspace=0, vspace=5></p>


Una serie es muy similar a un arreglo de NumPy (de hecho, está construida sobre el objeto de arreglo de NumPy). Lo que diferencia el arreglo de una Serie es que una Serie puede tener etiquetas de eje, lo que significa que puede ser indexada por una etiqueta, en lugar de solo una ubicación numérica. Tampoco necesita contener datos numéricos, puede contener cualquier objeto Python arbitrario.

Una serie puede ser creada a partir de un arreglo, de una lista o de un diccionario.

In [10]:
# Creando una serie

labels = ['a','b','c']
my_list = [10,20,30]

arr = np.array([10,20,30])

d = { 'a' : 10 , 'b' : 20 , 'c' : 30 }


Serie = pd.Series( d )
Serie

a    10
b    20
c    30
dtype: int64

Los índices se utilizan de la misma manera que en las listas, diccionarios o arreglos:

In [11]:
# Llamando un elemento de la serie

Serie[ ['b','c'] ]

b    20
c    30
dtype: int64

Cuando operamos dos series tenemos que tener cuidado, ya que estas se operan a partir de las etiquetas, no de la posición que utilizen en esta:

In [12]:
# Operación simple entre series

ser_1 = pd.Series([1,2,3,4],index = ['USA', 'Germany','USSR', 'Japan'])
ser_2 = pd.Series([1,2,5,4],index = ['USA', 'Germany','Italy', 'Japan'])

ser_1+ser_2

Germany    4.0
Italy      NaN
Japan      8.0
USA        2.0
USSR       NaN
dtype: float64

<a id="section2"></a>
<h3>2. Dataframe</h3>
<hr>

Los DataFrames son el caballo de batalla de los pandas y están directamente inspirados en el lenguaje de programación R. Podemos pensar en un DataFrame como una matriz, donde cada columna es una serie. 

<p><img alt="Dataframe" width=450 src="https://vrzkj25a871bpq7t1ugcgmn9-wpengine.netdna-ssl.com/wp-content/uploads/2022/01/pandas-dataframe-integer-location.png", align="center", hspace=0, vspace=5></p>

Las columnas nos representan variables y las filas los datos, algunas veces indexados.

In [13]:
# Creando nuestro primer dataframe

arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

df_1 = pd.DataFrame( data = arr )
df_2 = pd.DataFrame( data = arr , index = ["d_1","d_2","d_3"] , columns = ["V_1","V_2","V_3","V_4"])
df_2

V_1  V_2  V_3  V_4
d_1    1    2    3    4
d_2    5    6    7    8
d_3    9   10   11   12

#### Leyendo y guardando ficheros
No solo podemos crear dataframes a partir de objetos creados en Python, además podemos leer datos de nuestra propia base datos o de un directorio externo.

In [14]:
# Leyendo un archivo .csv

df_covid19 = pd.read_csv("cases_country.csv")
df_covid19

Country_Region          Last_Update        Lat       Long_  \
0             Australia  2020-05-29 17:32:50 -25.000000  133.000000   
1               Austria  2020-05-29 17:32:50  47.516200   14.550100   
2                Canada  2020-05-29 17:32:50  60.001000  -95.001000   
3                 China  2020-05-29 17:32:50  30.592800  114.305500   
4               Denmark  2020-05-29 17:32:50  56.263900    9.501800   
..                  ...                  ...        ...         ...   
183  West Bank and Gaza  2020-05-29 17:32:50  31.952200   35.233200   
184      Western Sahara  2020-05-29 17:32:50  24.215500  -12.885800   
185               Yemen  2020-05-29 17:32:50  15.552727   48.516388   
186              Zambia  2020-05-29 17:32:50 -13.133897   27.849332   
187            Zimbabwe  2020-05-29 17:32:50 -19.015438   29.154857   

     Confirmed  Deaths  Recovered   Active  Incident_Rate  People_Tested  \
0       7173.0   103.0     6582.0    488.0      28.173938            NaN   
1      16655.0   668.0    15347.0    640.0     184.924054            NaN   
2      90658.0  7042.0    47454.0  36162.0     239.483077            NaN   
3      84119.0  4638.0    79380.0    101.0       5.988497            NaN   
4      11793.0   568.0    10438.0    787.0     203.601290            NaN   
..         ...     ...        ...      ...            ...            ...   
183      446.0     3.0      368.0     75.0       8.742671            NaN   
184        9.0     1.0        6.0      2.0       1.506705            NaN   
185      283.0    65.0       11.0    207.0       0.948838            NaN   
186     1057.0     7.0      779.0    271.0       5.749579            NaN   
187      149.0     4.0       28.0    117.0       1.002494            NaN   

     People_Hospitalized  Mortality_Rate  UID ISO3  
0                    NaN        1.435940   36  AUS  
1                    NaN        4.010808   40  AUT  
2                    NaN        7.767654  124  CAN  
3                    NaN        5.513618  156  CHN  
4                    NaN        4.816417  208  DNK  
..                   ...             ...  ...  ...  
183                  NaN        0.672646  275  PSE  
184                  NaN       11.111111  732  ESH  
185                  NaN       22.968198  887  YEM  
186                  NaN        0.662252  894  ZMB  
187                  NaN        2.684564  716  ZWE  

[188 rows x 14 columns]

In [15]:
# Leyendo archivo desde url

df_covid19_url = pd.read_csv("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv")
df_covid19_url

Province/State         Country/Region        Lat       Long  1/22/20  \
0              NaN            Afghanistan  33.000000  65.000000        0   
1              NaN                Albania  41.153300  20.168300        0   
2              NaN                Algeria  28.033900   1.659600        0   
3              NaN                Andorra  42.506300   1.521800        0   
4              NaN                 Angola -11.202700  17.873900        0   
..             ...                    ...        ...        ...      ...   
261            NaN  Sao Tome and Principe   0.186360   6.613081        0   
262            NaN                  Yemen  15.552727  48.516388        0   
263            NaN                Comoros -11.645500  43.333300        0   
264            NaN             Tajikistan  38.861034  71.276093        0   
265            NaN                Lesotho -29.609988  28.233608        0   

     1/23/20  1/24/20  1/25/20  1/26/20  1/27/20  ...  6/8/20  6/9/20  \
0          0        0        0        0        0  ...   20917   21459   
1          0        0        0        0        0  ...    1263    1299   
2          0        0        0        0        0  ...   10265   10382   
3          0        0        0        0        0  ...     852     852   
4          0        0        0        0        0  ...      92      96   
..       ...      ...      ...      ...      ...  ...     ...     ...   
261        0        0        0        0        0  ...     513     514   
262        0        0        0        0        0  ...     496     524   
263        0        0        0        0        0  ...     141     141   
264        0        0        0        0        0  ...    4609    4690   
265        0        0        0        0        0  ...       4       4   

     6/10/20  6/11/20  6/12/20  6/13/20  6/14/20  6/15/20  6/16/20  6/17/20  
0      22142    22890    23546    24102    24766    25527    26310    26874  
1       1341     1385     1416     1464     1521     1590     1672     1722  
2      10484    10589    10698    10810    10919    11031    11147    11268  
3        852      852      853      853      853      853      854      854  
4        113      118      130      138      140      142      148      155  
..       ...      ...      ...      ...      ...      ...      ...      ...  
261      611      632      639      659      661      662      671      683  
262      560      591      632      705      728      844      885      902  
263      162      162      163      176      176      176      197      197  
264     4763     4834     4902     4971     5035     5097     5160     5221  
265        4        4        4        4        4        4        4        4  

[266 rows x 152 columns]

In [16]:
# Guardando un archivo localmente

df_covid19_url.to_csv("df_covid19.csv" , index="False")

#### Selección por columnas
Como ahora estamos trabajando con matrices, podemos querer seleccionar tanto por variables (Columnas) como por datos (Filas), por lo cual existen distintas formas de indexación, la primera a ver será la indexación por columnas.

Si indexamos 1 columna, entonces obtenemos una serie por resultado, pero si indexamos una lista de columnas obtenemos un dataframe

In [17]:
# Seleccionando 1 columna

df_covid19["Country_Region"]

0               Australia
1                 Austria
2                  Canada
3                   China
4                 Denmark
              ...        
183    West Bank and Gaza
184        Western Sahara
185                 Yemen
186                Zambia
187              Zimbabwe
Name: Country_Region, Length: 188, dtype: object

In [18]:
# Seleccionando 4 columnas

df = df_covid19[ ["Country_Region","Confirmed","Deaths","Recovered"] ]
df

Country_Region  Confirmed  Deaths  Recovered
0             Australia     7173.0   103.0     6582.0
1               Austria    16655.0   668.0    15347.0
2                Canada    90658.0  7042.0    47454.0
3                 China    84119.0  4638.0    79380.0
4               Denmark    11793.0   568.0    10438.0
..                  ...        ...     ...        ...
183  West Bank and Gaza      446.0     3.0      368.0
184      Western Sahara        9.0     1.0        6.0
185               Yemen      283.0    65.0       11.0
186              Zambia     1057.0     7.0      779.0
187            Zimbabwe      149.0     4.0       28.0

[188 rows x 4 columns]

#### Trabajando con variables

 * Para generar una nueva variable (columna) basta con crearla como si estuvieramos seleccionandola, y asignarle su valor.
 * Para eliminar una variable se utiliza la función **.drop( )**
 * Podemos indexar condiciones para establecer condiciones sobre las variables
 

In [19]:
# Creando una nueva variable

df["Active"] = df["Confirmed"]-df["Deaths"]-df["Recovered"]

C:\Users\Familia\anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until


In [20]:
# Eliminando la variable

df = df.drop("Active" , axis = 1)
df

Country_Region  Confirmed  Deaths  Recovered
0             Australia     7173.0   103.0     6582.0
1               Austria    16655.0   668.0    15347.0
2                Canada    90658.0  7042.0    47454.0
3                 China    84119.0  4638.0    79380.0
4               Denmark    11793.0   568.0    10438.0
..                  ...        ...     ...        ...
183  West Bank and Gaza      446.0     3.0      368.0
184      Western Sahara        9.0     1.0        6.0
185               Yemen      283.0    65.0       11.0
186              Zambia     1057.0     7.0      779.0
187            Zimbabwe      149.0     4.0       28.0

[188 rows x 4 columns]

In [21]:
# Condicionando variables

df_high_deaths = df[ df["Deaths"]>10000 ]
df_high_deaths

Country_Region  Confirmed    Deaths  Recovered
6           France   186364.0   28665.0    67309.0
10           Italy   232248.0   33229.0   152844.0
16  United Kingdom   272606.0   38243.0     1171.0
17              US  1731035.0  102201.0   399991.0
18           Spain   238564.0   27121.0   150376.0
21          Brazil   438238.0   26754.0   177604.0

#### Indexación por filas

Para comenzar, podemos establecer que una de nuestras columnas sea el indice para nuestro dataframe, para esto utilizamos la funcion **.set_index( )**

In [22]:
# Escogiendo un índice

df = df.set_index("Country_Region")
df

Confirmed  Deaths  Recovered
Country_Region                                  
Australia              7173.0   103.0     6582.0
Austria               16655.0   668.0    15347.0
Canada                90658.0  7042.0    47454.0
China                 84119.0  4638.0    79380.0
Denmark               11793.0   568.0    10438.0
...                       ...     ...        ...
West Bank and Gaza      446.0     3.0      368.0
Western Sahara            9.0     1.0        6.0
Yemen                   283.0    65.0       11.0
Zambia                 1057.0     7.0      779.0
Zimbabwe                149.0     4.0       28.0

[188 rows x 3 columns]

Para escoger 1 o 2 datos, utilizamos la función **.loc[ ]**.

In [23]:
# Escogiendo datos particulares

df.loc[ ["Argentina","Chile"]  ]

Confirmed  Deaths  Recovered
Country_Region                              
Argentina         14702.0   510.0     4788.0
Chile             90638.0   944.0    38598.0

<a id="section3"></a>
<h3>3. Datos faltantes (Missing Data)</h3>
<hr>

Generalmente los datos vienen con valores faltantes en algunas de sus columnas, y esto puede traernos problema a la hora de trabajar y establecer criterios de decisión con la información que obtenemos de estos.

Debemos saber que hacer con la data que falta y cuándo hacerlo, para así no tener problemas a la hora de establecer un modelo, o obtener insights. 

Hay 3 formas usuales de trabajar con datos faltantes:
 
 1. La primera es simplemente eliminar las filas con datos faltantes, y evitarse el riesgo de asignar mal un valor. El problema que esto podría traer es que estamos omitiendo información relevante de nuestra muestra.
 2. La segunda es rellenar con algun valor determinado, ya sea la media, mediana u otro que nosotros consideremos. Aquí podríamos estar centralizando demasiado nuestros datos, y cuando las desviaciones son altas este método no es muy efectivo.
 3. Otro método consiste en utilizar modelos para tratar de predecir o remplanzar los datos faltantes, aunque esto podría tomarnos mucho tiempo y recursos.
 

<p><img alt="Multiple_Imputation" width=450 src="https://media.springernature.com/lw785/springer-static/image/chp%3A10.1007%2F978-3-319-43742-2_13/MediaObjects/339333_1_En_13_Fig3_HTML.gif", align="center", hspace=0, vspace=5></p>

En Python las funciones que nos ayudan a esto son **.dropna( )** para eliminar y la función **.fillna( )** para rellenar.

In [24]:
# Consideramos este dataframe

df = pd.DataFrame({'v_1':[1,2,np.nan],
                  'v_2':[5,np.nan,np.nan],
                  'v_3':[1,2,3]})
df

v_1  v_2  v_3
0  1.0  5.0    1
1  2.0  NaN    2
2  NaN  NaN    3

In [25]:
# Eliminando filas con NA

df.dropna()

v_1  v_2  v_3
0  1.0  5.0    1

In [26]:
# Eliminando columnas con NA

df.dropna(axis=1)

v_3
0    1
1    2
2    3

In [27]:
# Eliminando filas que tengan mas de n datos faltantes

n = 2
df.dropna( thresh=n , axis = 1)

# Esto se puede replicar para columnas con axis=1 en los argumentos

v_1  v_3
0  1.0    1
1  2.0    2
2  NaN    3

In [28]:
# Llenando con el promedio
for i in df.columns:
    df[i] = df[i].fillna( value = df[i].mean() )
df

v_1  v_2  v_3
0  1.0  5.0    1
1  2.0  5.0    2
2  1.5  5.0    3

<a id="section4"></a>
<h3>4. Agrupaciones (Groupby)</h3>
<hr>

Para agrupar los datos en varios dataframes utilizando valores que se repitan en alguna de sus variables, utilizamos la funcion **.groupby( )**

In [37]:
# Agrupamos el conjunto por paises

df = df_covid19_url.dropna()
countrys = df.groupby("Country/Region")
countrys

Cuando ya tenemos agrupados los datos por alguna variable podemos hacer diversas operaciones, entre ellas estan
 
 * Suma con la funcion **.sum( )**
 * Calcular el promedio con **.mean( )**
 * Calcular mínimo y máximo con **.max( )** y **.min( )** respectivamente.
 * Contar cuantos datos hay con **.count( )**
 * Realizar estadística descriptiva con **.describe( )**
 
Ademas con la función **.get_group( )** podemos obtener un dataframe específico.

In [30]:
# Hacemos una suma sobre los grupos

countrys.count()

Province/State  Lat  Long  1/22/20  1/23/20  1/24/20  1/25/20  \
Country/Region                                                                  
Australia                    8    8     8        8        8        8        8   
Canada                      14   14    14       14       14       14       14   
China                       33   33    33       33       33       33       33   
Denmark                      2    2     2        2        2        2        2   
France                      10   10    10       10       10       10       10   
Netherlands                  4    4     4        4        4        4        4   
United Kingdom              10   10    10       10       10       10       10   

                1/26/20  1/27/20  1/28/20  ...  6/8/20  6/9/20  6/10/20  \
Country/Region                             ...                            
Australia             8        8        8  ...       8       8        8   
Canada               14       14       14  ...      14      14       14   
China                33       33       33  ...      33      33       33   
Denmark               2        2        2  ...       2       2        2   
France               10       10       10  ...      10      10       10   
Netherlands           4        4        4  ...       4       4        4   
United Kingdom       10       10       10  ...      10      10       10   

                6/11/20  6/12/20  6/13/20  6/14/20  6/15/20  6/16/20  6/17/20  
Country/Region                                                                 
Australia             8        8        8        8        8        8        8  
Canada               14       14       14       14       14       14       14  
China                33       33       33       33       33       33       33  
Denmark               2        2        2        2        2        2        2  
France               10       10       10       10       10       10       10  
Netherlands           4        4        4        4        4        4        4  
United Kingdom       10       10       10       10       10       10       10  

[7 rows x 151 columns]

In [31]:
# Podemos obtener el dataframe de un elemento en particular

countrys.get_group("Australia").describe()

Lat        Long  1/22/20  1/23/20  1/24/20  1/25/20   1/26/20  \
count   8.000000    8.000000      8.0      8.0      8.0      8.0  8.000000   
mean  -31.996188  141.232788      0.0      0.0      0.0      0.0  0.500000   
std     8.822593   12.552927      0.0      0.0      0.0      0.0  1.069045   
min   -41.454500  115.860500      0.0      0.0      0.0      0.0  0.000000   
25%   -36.058525  136.661925      0.0      0.0      0.0      0.0  0.000000   
50%   -34.398650  145.466900      0.0      0.0      0.0      0.0  0.000000   
75%   -30.967050  149.561625      0.0      0.0      0.0      0.0  0.250000   
max   -12.463400  153.400000      0.0      0.0      0.0      0.0  3.000000   

        1/27/20   1/28/20  1/29/20  ...       6/8/20       6/9/20  \
count  8.000000  8.000000  8.00000  ...     8.000000     8.000000   
mean   0.625000  0.625000  0.75000  ...   908.375000   909.250000   
std    1.407886  1.407886  1.38873  ...  1047.891616  1049.218723   
min    0.000000  0.000000  0.00000  ...    29.000000    29.000000   
25%    0.000000  0.000000  0.00000  ...   198.000000   198.000000   
50%    0.000000  0.000000  0.00000  ...   519.500000   519.500000   
75%    0.250000  0.250000  1.00000  ...  1218.250000  1219.250000   
max    4.000000  4.000000  4.00000  ...  3114.000000  3117.000000   

           6/10/20      6/11/20     6/12/20      6/13/20      6/14/20  \
count     8.000000     8.000000     8.00000     8.000000     8.000000   
mean    910.625000   911.125000   911.75000   915.000000   916.875000   
std    1050.009923  1049.818547  1051.03918  1055.577161  1057.789128   
min      29.000000    29.000000    29.00000    29.000000    29.000000   
25%     198.000000   198.000000   198.00000   198.000000   198.000000   
50%     520.500000   521.000000   521.00000   521.000000   521.000000   
75%    1222.000000  1223.750000  1224.50000  1228.750000  1231.750000   
max    3117.000000  3115.000000  3119.00000  3128.000000  3131.000000   

           6/15/20      6/16/20      6/17/20  
count     8.000000     8.000000     8.000000  
mean    918.375000   921.250000   923.875000  
std    1059.680132  1062.349519  1064.952237  
min      29.000000    29.000000    29.000000  
25%     198.000000   198.000000   198.000000  
50%     521.000000   521.000000   521.500000  
75%    1234.000000  1240.000000  1244.500000  
max    3134.000000  3135.000000  3137.000000  

[8 rows x 150 columns]

In [32]:
df.columns

Index(['Province/State', 'Country/Region', 'Lat', 'Long', '1/22/20', '1/23/20',
       '1/24/20', '1/25/20', '1/26/20', '1/27/20',
       ...
       '6/8/20', '6/9/20', '6/10/20', '6/11/20', '6/12/20', '6/13/20',
       '6/14/20', '6/15/20', '6/16/20', '6/17/20'],
      dtype='object', length=152)

<a id="section5"></a>
<h3>5. Fusiones (Merges), Uniones (Joins) y Concatenaciones</h3>
<hr>
Las siguientes operaciones que veremos entre dataframes nos permiten realizar uniones de algún tipo con 2 dataframes.

#### Join

Entre las tres operaciones de DataFrame, **join()** es la más sencilla y la que menos control nos da sobre la unión. Combina todas las columnas existentes en dos tablas, y las columnas en común las renombrara con un *lsuffix* y un *rsuffix* definidos.

Existen a su ves varios tipos de join, los cuales se deben definir en los argumentos de la función con un argumento *how*.

<p><img alt="Join" width=750 src="https://miro.medium.com/max/1400/1*-I_1qa5TIiB5eNYxnodfAA.png", align="center", hspace=0, vspace=5></p>


```Python
df.join(self, how='left', lsuffix='', rsuffix='')
```


In [33]:
# Definimos los dataframes para el join()

df_1 = pd.DataFrame({'A': ['A0', 'A1', 'A2'],
                     'B': ['B0', 'B1', 'B2']},
                    index=['K0', 'K1', 'K2'])

df_2 = pd.DataFrame({'B': ['B0', 'B1', 'B2'],
                     'C': ['C0', 'C2', 'C3'],
                     'D': ['D0', 'D2', 'D3']},
                    index=['K0', 'K2', 'K3'])

In [34]:
# Visualizamos el primer Dataframe

df_1

A   B
K0  A0  B0
K1  A1  B1
K2  A2  B2

In [35]:
# Visualizamos el segundo Dataframe

df_2

B   C   D
K0  B0  C0  D0
K2  B1  C2  D2
K3  B2  C3  D3

In [36]:
# Realizamos el join()

df_join = df_1.join(df_2, how='outer', lsuffix='_1', rsuffix='_2')
df_join

A  B_1  B_2    C    D
K0   A0   B0   B0   C0   D0
K1   A1   B1  NaN  NaN  NaN
K2   A2   B2   B1   C2   D2
K3  NaN  NaN   B2   C3   D3

#### Merge

Similar al join, el **merge()** también combina todas las columnas de dos tablas, con las columnas comunes renombradas con los sufijos definidos. Sin embargo, el merge proporciona tres formas de control flexible sobre la alineación en filas:

 1. La primera forma es usar *on = COLUMN NAME*, aquí la columna dada debe ser la columna común en ambas tablas.
 
 2. La segunda forma es usar *left_on = COLUMN NAME* y *right_on = COLUMN NAME*, y permite alinear las dos tablas usando dos columnas diferentes. 
 
 3. La tercera forma es usar *left_index = True* y *right_index = True*, y las dos tablas están alineadas en función de su índice.
 
 
 
 ```Python
 pd.merge(left, right, how='inner', on=None, left_on=None, right_on=None,
         left_index=False, right_index=False, suffixes=('_x', '_y'))
    ```

#### Concatenation

A diferencia del join() y del merge(), que por defecto operan en columnas, **concat()** puede realizar tambien operaciones de union para filas. El argumento en este caso es una lista con dataframes.


.


 * *Axis = 1*
<p><img alt="Join" width=450 src="https://miro.medium.com/max/1400/1*LoUq8uZrbg_tO3t4tqZfqg.png", align="center", hspace=0, vspace=5></p>


 * *Axis = 0*
<p><img alt="Join" width=450 src="https://miro.medium.com/max/1400/1*bQ3Bl6_N_V4er6XZxVxIZA.png", align="center", hspace=0, vspace=5></p>


```Python
pd.concat(objs, axis=0, join='outer', join_axes=None, ignore_index=False, keys=None)
```

#### ¡Motivense a seguir probando distintas combinaciones en los argumentos de las funciones!

**Guía de Uniones:** <a href="https://pandas.pydata.org/pandas-docs/stable/user_guide/merging.html">Click aquí</a>